from setuptools import setup

setup(name='deepclust',
      version='0.1',
      description='Various tools to handle data and simmulations',
      url='http://github.com/zekearneodo/deepclust',
      author='Zeke Arneodo',
      author_email='earneodo@ucsd.edu',
      license='MIT',
      packages=['deepclust'],
      install_requires=['numpy',
                        'pandas>=0.23',
                        'more_itertools',
                        'peakutils>=1.3',
                        'scipy',
                        'matplotlib',
                        'pyqt5',
                        'librosa',
                        'tqdm',
                        'pyqtgraph'],
      zip_safe=False)
